version: '3.8'

services:
  # React Frontend Development Server
  frontend:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
    command: npm start
    stdin_open: true
    tty: true
    networks:
      - portfolio-network

  # Express API Backend
  api:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
    command: npm run api
    depends_on:
      - frontend
    networks:
      - portfolio-network

  # Full Development Environment (both frontend and api)
  dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=3000
      - NODE_ENV=development
      - PORT=5000
    command: npm run dev
    stdin_open: true
    tty: true
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  node_modules: